library(nlsCompare)
machid<-machineId()
setup_dir()
spreadsheet <- create_db()
spreadsheet_error <- create_elog()
csv_exists()
run(machid,spreadsheet,spreadsheet_error)
write_csvs(spreadsheet,spreadsheet_error)
rm_nls()

