library(nlsCompare)
machid<-machineId()
setup_dir()
#getwd()
spreadsheet <- create_db()
spreadsheet_error <- create_elog()
csv_exists()
run(machid,spreadsheet,spreadsheet_error) # uphill search?>positive
write_csvs(spreadsheet,spreadsheet_error)
rm_nls()